### PR TITLE
fix: unpacking error when using a list of audio

### PR DESCRIPTION
**Pull request by yoyololicon**

### CODE REVIEW

**Comment by gudgud96** [comment]
Any error you encounter on your side?
`load_audio_task` should return a tuple `wav_data, SAMPLE_RATE`, so `x` should be a list of tuples. Do correct me if I am wrong.

**Comment by yoyololicon** [comment]
Oh, I didn't use `load_audio_trask` but the `get_embeddings` directly.
I would suggest updating the docstring.

**Comment by gudgud96** [comment]
Ahh, got it. See where you are coming from. I will refactor the code accordingly, thanks!

**Comment by gudgud96** [comment]
Refactored in https://github.com/gudgud96/frechet-audio-distance/pull/8, close this issue for now.

**Pull request closed without merging**
